### ISSUE TITLE
关于数据预处理

### ISSUE THREAD

**Issue by syw1996** [YueChenkkk/CSN_SAPR#1]
您好，我想问一下data_prep.py中单词距离计算部分代码
`if pos[0] == ws:
            w_d = ws * 2`
wd为词级别cand到quote距离，想请教一下，当cand位置在quote时，这么算的原理，多谢

**Comment by YueChenkkk** [comment]
您好，感谢您的提问。
这其实是一个比较随意的处理，目的是让出现在quote中的cand有一个较大的词级别距离，从而使它不容易被选为nearest mention。因为在quote中的cand通常不是speaker，除非“我是xxx”这种情况。我的想法是，如果在quote附近有其他mention，则优先选择这些quote之外的mention；如果quote附近找不到mention，也可以选择quote内部的mention（在《平凡的世界》数据集中这通常意味着对应cand不是speaker）。
我当时认为，“quote附近”的定义应该跟截取的文本窗口长度有关，对于不同的文学类型，它具有不同的取值。像《平凡的世界》这样的传统文学作品，quote附近小范围内经常无法找到说话人的mention，“quote附近”的定义应该适当放宽。而对于网络文学，quote前一句往往可以找到“xxx说：”的pattern，“quote附近”的定义应该缩窄。
不知道我有没有解释清楚，请您随时提问~

**Comment by syw1996** [comment]
> “

非常感谢解答

**Comment by syw1996** [comment]
> 您好，感谢您的提问。 这其实是一个比较随意的处理，目的是让出现在quote中的cand有一个较大的词级别距离，从而使它不容易被选为nearest mention。因为在quote中的cand通常不是speaker，除非“我是xxx”这种情况。我的想法是，如果在quote附近有其他mention，则优先选择这些quote之外的mention；如果quote附近找不到mention，也可以选择quote内部的mention（在《平凡的世界》数据集中这通常意味着对应cand不是speaker）。 我当时认为，“quote附近”的定义应该跟截取的文本窗口长度有关，对于不同的文学类型，它具有不同的取值。像《平凡的世界》这样的传统文学作品，quote附近小范围内经常无法找到说话人的mention，“quote附近”的定义应该适当放宽。而对于网络文学，quote前一句往往可以找到“xxx说：”的pattern，“quote附近”的定义应该缩窄。 不知道我有没有解释清楚，请您随时提问~

非常感谢解答
